# Generated by Django 3.1.3 on 2020-11-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='profile',
            new_name='developer',
        ),
    ]
