# Generated by Django 3.1.3 on 2020-11-27 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0004_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='project',
            new_name='post',
        ),
        migrations.AddField(
            model_name='project',
            name='vote',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rating_app.rating'),
        ),
    ]
