# Generated by Django 3.1.3 on 2020-11-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0005_auto_20201127_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='vote',
        ),
        migrations.AlterField(
            model_name='rating',
            name='content',
            field=models.PositiveIntegerField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default=1),
        ),
        migrations.AlterField(
            model_name='rating',
            name='design',
            field=models.PositiveIntegerField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default=1),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user_expirience',
            field=models.PositiveIntegerField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default=1),
        ),
    ]
