# Generated by Django 3.1.3 on 2020-11-27 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0006_auto_20201127_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rating_app.rating'),
        ),
    ]
