# Generated by Django 3.1.3 on 2020-11-28 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0007_project_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='vote',
        ),
        migrations.AddField(
            model_name='project',
            name='new_vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rating_app.rating'),
        ),
    ]
