# Generated by Django 3.1.3 on 2020-11-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0008_auto_20201128_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='new_vote',
        ),
    ]
