# Generated by Django 3.1.3 on 2020-11-28 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0009_remove_project_new_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_on',
            new_name='uploaded_on',
        ),
    ]
