# Generated by Django 3.1.3 on 2020-11-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0010_auto_20201128_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='content',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='design',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user_expirience',
        ),
        migrations.AddField(
            model_name='rating',
            name='content_vote',
            field=models.PositiveIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=1),
        ),
        migrations.AddField(
            model_name='rating',
            name='design_vote',
            field=models.PositiveIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=1),
        ),
        migrations.AddField(
            model_name='rating',
            name='ux_vote',
            field=models.PositiveIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=1),
        ),
    ]
