# Generated by Django 3.1.3 on 2020-11-28 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0011_auto_20201128_0923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Post',
        ),
    ]
