# Generated by Django 3.1.3 on 2020-11-29 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0015_profilemerch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemerch',
            name='projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating_app.post'),
        ),
    ]
