# Generated by Django 3.1.3 on 2020-11-29 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0016_auto_20201129_1156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileMerch',
        ),
    ]
